# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buscar}
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jarrett"]
  s.date = %q{2011-08-24}
  s.description = %q{Simplifies searching, sorting, and pagination of ActiveRecord models. Includes a model class and a view helper.}
  s.email = %q{jarrettcolby@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "buscar.gemspec",
    "lib/buscar.rb",
    "lib/buscar/helpers.rb",
    "lib/buscar/index.rb",
    "lib/buscar/railtie.rb",
    "spec/blueprint.rb",
    "spec/helpers_spec.rb",
    "spec/index_spec.rb",
    "spec/matchers.rb",
    "spec/spec_helper.rb",
    "spec/test_db.rb"
  ]
  s.homepage = %q{http://github.com/jarrett/buscar}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Searching, sorting, and pagination for Rails}
  s.test_files = [
    "spec/blueprint.rb",
    "spec/helpers_spec.rb",
    "spec/index_spec.rb",
    "spec/matchers.rb",
    "spec/spec_helper.rb",
    "spec/test_db.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.2.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_development_dependency(%q<faker>, [">= 0.3.1"])
      s.add_development_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_development_dependency(%q<actionpack>, [">= 3.0.3"])
      s.add_development_dependency(%q<activerecord>, [">= 3.0.3"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.2"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0.2"])
      s.add_development_dependency(%q<actionpack>, [">= 3.0.2"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_development_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_development_dependency(%q<faker>, [">= 0.3.1"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.2"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rspec>, [">= 2.2.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_dependency(%q<faker>, [">= 0.3.1"])
      s.add_dependency(%q<activesupport>, [">= 3.0.3"])
      s.add_dependency(%q<actionpack>, [">= 3.0.3"])
      s.add_dependency(%q<activerecord>, [">= 3.0.3"])
      s.add_dependency(%q<activesupport>, [">= 3.0.2"])
      s.add_dependency(%q<activerecord>, [">= 3.0.2"])
      s.add_dependency(%q<actionpack>, [">= 3.0.2"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
      s.add_dependency(%q<machinist>, [">= 1.0.6"])
      s.add_dependency(%q<faker>, [">= 0.3.1"])
      s.add_dependency(%q<webrat>, [">= 0.7.2"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rspec>, [">= 2.2.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<machinist>, [">= 1.0.6"])
    s.add_dependency(%q<faker>, [">= 0.3.1"])
    s.add_dependency(%q<activesupport>, [">= 3.0.3"])
    s.add_dependency(%q<actionpack>, [">= 3.0.3"])
    s.add_dependency(%q<activerecord>, [">= 3.0.3"])
    s.add_dependency(%q<activesupport>, [">= 3.0.2"])
    s.add_dependency(%q<activerecord>, [">= 3.0.2"])
    s.add_dependency(%q<actionpack>, [">= 3.0.2"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.2.5"])
    s.add_dependency(%q<machinist>, [">= 1.0.6"])
    s.add_dependency(%q<faker>, [">= 0.3.1"])
    s.add_dependency(%q<webrat>, [">= 0.7.2"])
  end
end

