# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buscar}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jarrett"]
  s.date = %q{2010-10-19}
  s.description = %q{Simplifies searching, sorting, and pagination of ActiveRecord models. Includes a model class and a view helper.}
  s.email = %q{jarrettcolby@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "buscar.gemspec",
     "lib/buscar.rb",
     "lib/buscar/helpers.rb",
     "lib/buscar/index.rb",
     "spec/.rspec",
     "spec/blueprint.rb",
     "spec/helpers_spec.rb",
     "spec/index_spec.rb",
     "spec/matchers.rb",
     "spec/spec_helper.rb",
     "spec/test_db.rb"
  ]
  s.homepage = %q{http://github.com/jarrett/buscar}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Searching, sorting, and pagination for Rails}
  s.test_files = [
    "spec/blueprint.rb",
     "spec/helpers_spec.rb",
     "spec/index_spec.rb",
     "spec/matchers.rb",
     "spec/spec_helper.rb",
     "spec/test_db.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

